In [1]:
import numpy as np
import pandas as pd

In [13]:
df=pd.read_csv('MegaMart_sales.csv')
df.shape

(59, 8)

In [14]:
df_new=pd.read_csv('MegaMart_newsales.csv')
df_new.shape

(9, 8)

#### Combining two data frames
Question 1: Some of the orders are stored in another csv file named `megamart_new sales`. Read the csv file, store it in a data frame and add it to the `megamart_sales` data frame. Find the total sales value of the category 'Office Supplies'  after combining the dataframes

    a)7970
    b)6964
    c)7494
    d)6076

In [15]:
#your code here
df3=pd.concat([df,df_new],axis=0)
df3

,Order ID,Product Name,Discount,Sales,Profit,Quantity,Category,Sub-Category
0,AZ-2011-1029887,"Novimex Color Coded Labels, 5000 Label Set",0.0,26,7,2,Office Supplies,Labels
1,AZ-2011-107716,"Deflect-O Door Stop, Erganomic",0.0,85,15,2,Furniture,Furnishings
2,AZ-2011-1087704,"Belkin Flash Drive, Bluetooth",0.0,294,109,7,Technology,Accessories
3,AZ-2011-1372644,"Panasonic Printer, Durable",0.0,800,168,3,Technology,Machines
4,AZ-2011-1362199,"Sanford Pens, Fluorescent",0.5,25,-11,4,Office Supplies,Art
...,...,...,...,...,...,...,...,...
4,AZ-2011-1967754,"Logitech Numeric Keypad, USB",0.0,93,40,2,Technology,Accessories
5,AZ-2011-1976919,"Boston Markers, Blue",0.0,132,54,5,Office Supplies,Art
6,AZ-2011-2001312,"Avery Binding Machine, Clear",0.0,97,12,2,Office Supplies,Binders
7,AZ-2011-2002251,"SanDisk Computer Printout Paper, 8.5 x 11",0.0,136,15,4,Office Supplies,Paper
8,AZ-2011-201891,"Cameo Clasp Envelope, with clear poly window",0.0,52,19,4,Office Supplies,Envelopes

In [16]:
df3.groupby(by='Category').sum

                 Discount  Sales  Profit  Quantity
Category
Furniture             1.3   2460     333        36
Office Supplies       4.7   7970    1338       169
Technology            0.0   8588    2278        60

#### Dropping duplicates
Question 2: There are some duplicate rows in the data frame. Drop these rows and calculate the total sales value of the category Office Supplies.

    a)7156
    b)6496
    c)6964
    d)6023

In [19]:
#your code here
df4=df3.drop_duplicates()
df4.groupby(by='Category').sum()

                 Discount  Sales  Profit  Quantity
Category
Furniture             1.3   2460     333        36
Office Supplies       3.6   6964    1045       149
Technology            0.0   7494    2001        50

#### Best category-sub category 
Question 3: Find the most profitable category and sub category combination based on the net profit.


    a)Furniture-Bookcases
    b)Office supplies-Appliances
    c)Office supplies-Storage
    d)Technology-Phones

In [21]:
#your code here
df3.groupby(by=['Category','Sub-Category']).sum()

                              Discount  Sales  Profit  Quantity
Category        Sub-Category
Furniture       Bookcases          0.1   1459     308        11
                Chairs             1.2    558     -49        13
                Furnishings        0.0    443      74        12
Office Supplies Appliances         0.1   1819     229         8
                Art                2.0   1612     283        58
                Binders            0.5    934     158        33
                Envelopes          0.0    146      35         9
                Fasteners          0.0     28      10         2
                Labels             0.0    166      30        15
                Paper              0.0    136      15         4
                Storage            2.1   2767     475        29
                Supplies           0.0    362     103        11
Technology      Accessories        0.0   1347     324        25
                Copiers            0.0    442       0         3
                Machines           0.0   1600     336         6
                Phones             0.0   5199    1618        26

#### Invalid order IDs
Question 4: How many invalid order IDs are there in the data frame. An order id is of the form AZ-2011-Y where Y represents a whole number. A Order ID is said to be valid only if Y consists of 7 digits. Find the number of valid order order IDs in the data frame.
    
    a)6
    b)7
    c)8
    d)9

In [23]:
df3.head()

,Order ID,Product Name,Discount,Sales,Profit,Quantity,Category,Sub-Category
0,AZ-2011-1029887,"Novimex Color Coded Labels, 5000 Label Set",0.0,26,7,2,Office Supplies,Labels
1,AZ-2011-107716,"Deflect-O Door Stop, Erganomic",0.0,85,15,2,Furniture,Furnishings
2,AZ-2011-1087704,"Belkin Flash Drive, Bluetooth",0.0,294,109,7,Technology,Accessories
3,AZ-2011-1372644,"Panasonic Printer, Durable",0.0,800,168,3,Technology,Machines
4,AZ-2011-1362199,"Sanford Pens, Fluorescent",0.5,25,-11,4,Office Supplies,Art

In [30]:
#your code here
count=0
for i in df3['Order ID']:
    j=i[8:]
    if len(j)!=7 or '.' in j:
        count+=1
print(count)

7

#### Occurence of furniture in top 25 sales
Question 5: Find the top 25 orders based on sales value and find the number of orders which belong to furniture category.

    a)2
    b)3
    c)4
    d)5

In [31]:
#your code here
df3.head()

,Order ID,Product Name,Discount,Sales,Profit,Quantity,Category,Sub-Category
0,AZ-2011-1029887,"Novimex Color Coded Labels, 5000 Label Set",0.0,26,7,2,Office Supplies,Labels
1,AZ-2011-107716,"Deflect-O Door Stop, Erganomic",0.0,85,15,2,Furniture,Furnishings
2,AZ-2011-1087704,"Belkin Flash Drive, Bluetooth",0.0,294,109,7,Technology,Accessories
3,AZ-2011-1372644,"Panasonic Printer, Durable",0.0,800,168,3,Technology,Machines
4,AZ-2011-1362199,"Sanford Pens, Fluorescent",0.5,25,-11,4,Office Supplies,Art

In [42]:
df5=df3.sort_values('Sales',ascending=False)
df5.head(25)

,Order ID,Product Name,Discount,Sales,Profit,Quantity,Category,Sub-Category
30,AZ-2011-1410648,"Nokia Smart Phone, Full Size",0.0,1908,820,3,Technology,Phones
58,AZ-2011-176674,"Hoover Microwave, Red",0.1,1667,185,6,Office Supplies,Appliances
8,AZ-2011-1174243,"Nokia Audio Dock, with Caller ID",0.0,1334,200,8,Technology,Phones
20,AZ-2011-1322840,"Motorola Headset, with Caller ID",0.0,957,316,12,Technology,Phones
3,AZ-2011-1372644,"Panasonic Printer, Durable",0.0,800,168,3,Technology,Machines
28,AZ-2011-1372644,"Panasonic Printer, Durable",0.0,800,168,3,Technology,Machines
29,AZ-2011-1406494,"Fellowes Lockers, Industrial",0.1,748,283,4,Office Supplies,Storage
18,AZ-2011-1406494,"Fellowes Lockers, Industrial",0.1,748,283,4,Office Supplies,Storage
39,AZ-2011-1536006,"Logitech Keyboard, Programmable",0.0,666,66,9,Technology,Accessories
33,AZ-2011-1445262,"Apple Smart Phone, Cordless",0.0,636,140,1,Technology,Phones
31,AZ-2011-144325,"Bush Stackable Bookrack, Pine",0.0,630,132,5,Furniture,Bookcases
14,AZ-2011-1260928,"Eldon File Cart, Single Width",0.1,576,51,5,Office Supplies,Storage
12,AZ-2011-1253407,"Safco Stackable Bookrack, Pine",0.1,541,156,4,Furniture,Bookcases
48,AZ-2011-1672552,"Binney & Smith Sketch Pad, Blue",0.0,510,132,11,Office Supplies,Art
41,AZ-2011-1584049,"Brother Ink, Laser",0.0,442,0,3,Technology,Copiers
52,AZ-2011-1722024,"Cisco Audio Dock, VoIP",0.0,364,142,2,Technology,Phones
0,AZ-2011-1902971,"Wilson Jones Binding Machine, Clear",0.0,339,102,7,Office Supplies,Binders
17,AZ-2011-130330,"Office Star Chairmat, Adjustable",0.1,307,99,5,Furniture,Chairs
13,AZ-2011-1087704,"Belkin Flash Drive, Bluetooth",0.0,294,109,7,Technology,Accessories
2,AZ-2011-1087704,"Belkin Flash Drive, Bluetooth",0.0,294,109,7,Technology,Accessories
1,AZ-2011-1916360,"Dania 3-Shelf Cabinet, Mobile",0.0,288,20,2,Furniture,Bookcases
11,AZ-2011-1240916,"Boston Canvas, Water Color",0.0,284,43,5,Office Supplies,Art
34,AZ-2011-145488,"Rogers File Cart, Industrial",0.4,255,-98,3,Office Supplies,Storage
6,AZ-2011-1116129,"Avery Binding Machine, Durable",0.0,252,15,5,Office Supplies,Binders
42,AZ-2011-1584987,"Tenex File Cart, Industrial",0.1,241,24,2,Office Supplies,Storage

#### And operation
Question 6: Among the orders with sales>250 and profit>50, find the product name of the fourth highest order based on sales value.

    a)Motorola Headset, with Caller ID
    b)Panasonic Printer, Durable	
    c)Hoover Microwave, Red	
    d)Fellowes Lockers, Industrial

In [45]:
#your code here
df6=df3[(df3['Sales']>250) & (df3['Profit']>50)]

In [46]:
df6.sort_values('Sales',ascending=False)

,Order ID,Product Name,Discount,Sales,Profit,Quantity,Category,Sub-Category
30,AZ-2011-1410648,"Nokia Smart Phone, Full Size",0.0,1908,820,3,Technology,Phones
58,AZ-2011-176674,"Hoover Microwave, Red",0.1,1667,185,6,Office Supplies,Appliances
8,AZ-2011-1174243,"Nokia Audio Dock, with Caller ID",0.0,1334,200,8,Technology,Phones
20,AZ-2011-1322840,"Motorola Headset, with Caller ID",0.0,957,316,12,Technology,Phones
28,AZ-2011-1372644,"Panasonic Printer, Durable",0.0,800,168,3,Technology,Machines
3,AZ-2011-1372644,"Panasonic Printer, Durable",0.0,800,168,3,Technology,Machines
18,AZ-2011-1406494,"Fellowes Lockers, Industrial",0.1,748,283,4,Office Supplies,Storage
29,AZ-2011-1406494,"Fellowes Lockers, Industrial",0.1,748,283,4,Office Supplies,Storage
39,AZ-2011-1536006,"Logitech Keyboard, Programmable",0.0,666,66,9,Technology,Accessories
33,AZ-2011-1445262,"Apple Smart Phone, Cordless",0.0,636,140,1,Technology,Phones
31,AZ-2011-144325,"Bush Stackable Bookrack, Pine",0.0,630,132,5,Furniture,Bookcases
14,AZ-2011-1260928,"Eldon File Cart, Single Width",0.1,576,51,5,Office Supplies,Storage
12,AZ-2011-1253407,"Safco Stackable Bookrack, Pine",0.1,541,156,4,Furniture,Bookcases
48,AZ-2011-1672552,"Binney & Smith Sketch Pad, Blue",0.0,510,132,11,Office Supplies,Art
52,AZ-2011-1722024,"Cisco Audio Dock, VoIP",0.0,364,142,2,Technology,Phones
0,AZ-2011-1902971,"Wilson Jones Binding Machine, Clear",0.0,339,102,7,Office Supplies,Binders
17,AZ-2011-130330,"Office Star Chairmat, Adjustable",0.1,307,99,5,Furniture,Chairs
13,AZ-2011-1087704,"Belkin Flash Drive, Bluetooth",0.0,294,109,7,Technology,Accessories
2,AZ-2011-1087704,"Belkin Flash Drive, Bluetooth",0.0,294,109,7,Technology,Accessories

#### Column manipulation
Question 7: Remove the orders with negative profit by dropping the corresponding rows with negative `Profit`. Find the product that makes the lowest profit per Quantity in the Technology category.

    a) Nokia Audio Dock, with Caller ID
    b) Logitech Keyboard, Programmable
    c) Motorola Headset, with Caller ID
    d) Belkin Flash Drive, Bluetooth

In [60]:
#your code here
df7=df3.sort_values('Profit')

In [61]:
df7

,Order ID,Product Name,Discount,Sales,Profit,Quantity,Category,Sub-Category
34,AZ-2011-145488,"Rogers File Cart, Industrial",0.4,255,-98,3,Office Supplies,Storage
21,AZ-2011-1328316,"Office Star Bag Chairs, Set of Two",0.5,87,-78,3,Furniture,Chairs
24,AZ-2011-1335871,"Tenex Shelving, Blue",0.5,82,-74,3,Office Supplies,Storage
43,AZ-2011-1589827,"Novimex Steel Folding Chair, Red",0.6,164,-70,5,Furniture,Chairs
44,AZ-2011-1603295,"Ibico Binder Covers, Clear",0.5,20,-17,3,Office Supplies,Binders
...,...,...,...,...,...,...,...,...
8,AZ-2011-1174243,"Nokia Audio Dock, with Caller ID",0.0,1334,200,8,Technology,Phones
18,AZ-2011-1406494,"Fellowes Lockers, Industrial",0.1,748,283,4,Office Supplies,Storage
29,AZ-2011-1406494,"Fellowes Lockers, Industrial",0.1,748,283,4,Office Supplies,Storage
20,AZ-2011-1322840,"Motorola Headset, with Caller ID",0.0,957,316,12,Technology,Phones
30,AZ-2011-1410648,"Nokia Smart Phone, Full Size",0.0,1908,820,3,Technology,Phones

In [62]:
d8=df7[(df7.Profit>0) & (df7.Category=='Technology')]
d8

,Order ID,Product Name,Discount,Sales,Profit,Quantity,Category,Sub-Category
4,AZ-2011-1967754,"Logitech Numeric Keypad, USB",0.0,93,40,2,Technology,Accessories
39,AZ-2011-1536006,"Logitech Keyboard, Programmable",0.0,666,66,9,Technology,Accessories
2,AZ-2011-1087704,"Belkin Flash Drive, Bluetooth",0.0,294,109,7,Technology,Accessories
13,AZ-2011-1087704,"Belkin Flash Drive, Bluetooth",0.0,294,109,7,Technology,Accessories
33,AZ-2011-1445262,"Apple Smart Phone, Cordless",0.0,636,140,1,Technology,Phones
52,AZ-2011-1722024,"Cisco Audio Dock, VoIP",0.0,364,142,2,Technology,Phones
3,AZ-2011-1372644,"Panasonic Printer, Durable",0.0,800,168,3,Technology,Machines
28,AZ-2011-1372644,"Panasonic Printer, Durable",0.0,800,168,3,Technology,Machines
8,AZ-2011-1174243,"Nokia Audio Dock, with Caller ID",0.0,1334,200,8,Technology,Phones
20,AZ-2011-1322840,"Motorola Headset, with Caller ID",0.0,957,316,12,Technology,Phones
30,AZ-2011-1410648,"Nokia Smart Phone, Full Size",0.0,1908,820,3,Technology,Phones

In [ ]:
25,7.33,26.33,15