#### This is the Credit EDA Case Study Submission by Souvik and Megha

In [1]:
# Filtering out the warnings

import warnings

warnings.filterwarnings('ignore')

In [2]:
# Importing the required libraries

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

#### Reading the Dataset 'application_data.csv'

In [3]:
app=pd.read_csv('application_data.csv')

In [4]:
#Getting the feel of the data
app.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

#### Inspecting the dataframe for dimensions, null-values, and summary of different numeric columns.

In [5]:
#Number of rows and columns in the dataframe
app.shape

(307511, 122)

In [6]:
#column names
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
app.columns

Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='object', length=122)

In [7]:
# column-wise info of the dataframe
app.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Columns: 122 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(65), int64(41), object(16)
memory usage: 286.2+ MB

In [8]:
#see the data-types of each column
app.dtypes

SK_ID_CURR                        int64
TARGET                            int64
NAME_CONTRACT_TYPE               object
CODE_GENDER                      object
FLAG_OWN_CAR                     object
FLAG_OWN_REALTY                  object
CNT_CHILDREN                      int64
AMT_INCOME_TOTAL                float64
AMT_CREDIT                      float64
AMT_ANNUITY                     float64
AMT_GOODS_PRICE                 float64
NAME_TYPE_SUITE                  object
NAME_INCOME_TYPE                 object
NAME_EDUCATION_TYPE              object
NAME_FAMILY_STATUS               object
NAME_HOUSING_TYPE                object
REGION_POPULATION_RELATIVE      float64
DAYS_BIRTH                        int64
DAYS_EMPLOYED                     int64
DAYS_REGISTRATION               float64
DAYS_ID_PUBLISH                   int64
OWN_CAR_AGE                     float64
FLAG_MOBIL                        int64
FLAG_EMP_PHONE                    int64
FLAG_WORK_PHONE                   int64
FLAG_CONT_MOBILE                  int64
FLAG_PHONE                        int64
FLAG_EMAIL                        int64
OCCUPATION_TYPE                  object
CNT_FAM_MEMBERS                 float64
REGION_RATING_CLIENT              int64
REGION_RATING_CLIENT_W_CITY       int64
WEEKDAY_APPR_PROCESS_START       object
HOUR_APPR_PROCESS_START           int64
REG_REGION_NOT_LIVE_REGION        int64
REG_REGION_NOT_WORK_REGION        int64
LIVE_REGION_NOT_WORK_REGION       int64
REG_CITY_NOT_LIVE_CITY            int64
REG_CITY_NOT_WORK_CITY            int64
LIVE_CITY_NOT_WORK_CITY           int64
ORGANIZATION_TYPE                object
EXT_SOURCE_1                    float64
EXT_SOURCE_2                    float64
EXT_SOURCE_3                    float64
APARTMENTS_AVG                  float64
BASEMENTAREA_AVG                float64
YEARS_BEGINEXPLUATATION_AVG     float64
YEARS_BUILD_AVG                 float64
COMMONAREA_AVG                  float64
ELEVATORS_AVG                   float64
ENTRANCES_AVG                   float64
FLOORSMAX_AVG                   float64
FLOORSMIN_AVG                   float64
LANDAREA_AVG                    float64
LIVINGAPARTMENTS_AVG            float64
LIVINGAREA_AVG                  float64
NONLIVINGAPARTMENTS_AVG         float64
NONLIVINGAREA_AVG               float64
APARTMENTS_MODE                 float64
BASEMENTAREA_MODE               float64
YEARS_BEGINEXPLUATATION_MODE    float64
YEARS_BUILD_MODE                float64
COMMONAREA_MODE                 float64
ELEVATORS_MODE                  float64
ENTRANCES_MODE                  float64
FLOORSMAX_MODE                  float64
FLOORSMIN_MODE                  float64
LANDAREA_MODE                   float64
LIVINGAPARTMENTS_MODE           float64
LIVINGAREA_MODE                 float64
NONLIVINGAPARTMENTS_MODE        float64
NONLIVINGAREA_MODE              float64
APARTMENTS_MEDI                 float64
BASEMENTAREA_MEDI               float64
YEARS_BEGINEXPLUATATION_MEDI    float64
YEARS_BUILD_MEDI                float64
COMMONAREA_MEDI                 float64
ELEVATORS_MEDI                  float64
ENTRANCES_MEDI                  float64
FLOORSMAX_MEDI                  float64
FLOORSMIN_MEDI                  float64
LANDAREA_MEDI                   float64
LIVINGAPARTMENTS_MEDI           float64
LIVINGAREA_MEDI                 float64
NONLIVINGAPARTMENTS_MEDI        float64
NONLIVINGAREA_MEDI              float64
FONDKAPREMONT_MODE               object
HOUSETYPE_MODE                   object
TOTALAREA_MODE                  float64
WALLSMATERIAL_MODE               object
EMERGENCYSTATE_MODE              object
OBS_30_CNT_SOCIAL_CIRCLE        float64
DEF_30_CNT_SOCIAL_CIRCLE        float64
OBS_60_CNT_SOCIAL_CIRCLE        float64
DEF_60_CNT_SOCIAL_CIRCLE        float64
DAYS_LAST_PHONE_CHANGE          float64
FLAG_DOCUMENT_2                   int64
FLAG_DOCUMENT_3                   int64
FLAG_DOCUMENT_4                   int64
FLAG_DOCUMENT_5                   int64
FLAG_DOCUMENT_6                   int64
FLAG_DOCUMENT_7                   int64
FLAG_DOCUMENT_8                   int64
FLAG_DOCUMENT_9                   int64
FLAG_DOCUMENT_10                  int64
FLAG_DOCUMENT_11                  int64
FLAG_DOCUMENT_12                  int64
FLAG_DOCUMENT_13                  int64
FLAG_DOCUMENT_14                  int64
FLAG_DOCUMENT_15                  int64
FLAG_DOCUMENT_16                  int64
FLAG_DOCUMENT_17                  int64
FLAG_DOCUMENT_18                  int64
FLAG_DOCUMENT_19                  int64
FLAG_DOCUMENT_20                  int64
FLAG_DOCUMENT_21                  int64
AMT_REQ_CREDIT_BUREAU_HOUR      float64
AMT_REQ_CREDIT_BUREAU_DAY       float64
AMT_REQ_CREDIT_BUREAU_WEEK      float64
AMT_REQ_CREDIT_BUREAU_MON       float64
AMT_REQ_CREDIT_BUREAU_QRT       float64
AMT_REQ_CREDIT_BUREAU_YEAR      float64
dtype: object

In [9]:
app.isnull().sum()

SK_ID_CURR                           0
TARGET                               0
NAME_CONTRACT_TYPE                   0
CODE_GENDER                          0
FLAG_OWN_CAR                         0
FLAG_OWN_REALTY                      0
CNT_CHILDREN                         0
AMT_INCOME_TOTAL                     0
AMT_CREDIT                           0
AMT_ANNUITY                         12
AMT_GOODS_PRICE                    278
NAME_TYPE_SUITE                   1292
NAME_INCOME_TYPE                     0
NAME_EDUCATION_TYPE                  0
NAME_FAMILY_STATUS                   0
NAME_HOUSING_TYPE                    0
REGION_POPULATION_RELATIVE           0
DAYS_BIRTH                           0
DAYS_EMPLOYED                        0
DAYS_REGISTRATION                    0
DAYS_ID_PUBLISH                      0
OWN_CAR_AGE                     202929
FLAG_MOBIL                           0
FLAG_EMP_PHONE                       0
FLAG_WORK_PHONE                      0
FLAG_CONT_MOBILE                     0
FLAG_PHONE                           0
FLAG_EMAIL                           0
OCCUPATION_TYPE                  96391
CNT_FAM_MEMBERS                      2
REGION_RATING_CLIENT                 0
REGION_RATING_CLIENT_W_CITY          0
WEEKDAY_APPR_PROCESS_START           0
HOUR_APPR_PROCESS_START              0
REG_REGION_NOT_LIVE_REGION           0
REG_REGION_NOT_WORK_REGION           0
LIVE_REGION_NOT_WORK_REGION          0
REG_CITY_NOT_LIVE_CITY               0
REG_CITY_NOT_WORK_CITY               0
LIVE_CITY_NOT_WORK_CITY              0
ORGANIZATION_TYPE                    0
EXT_SOURCE_1                    173378
EXT_SOURCE_2                       660
EXT_SOURCE_3                     60965
APARTMENTS_AVG                  156061
BASEMENTAREA_AVG                179943
YEARS_BEGINEXPLUATATION_AVG     150007
YEARS_BUILD_AVG                 204488
COMMONAREA_AVG                  214865
ELEVATORS_AVG                   163891
ENTRANCES_AVG                   154828
FLOORSMAX_AVG                   153020
FLOORSMIN_AVG                   208642
LANDAREA_AVG                    182590
LIVINGAPARTMENTS_AVG            210199
LIVINGAREA_AVG                  154350
NONLIVINGAPARTMENTS_AVG         213514
NONLIVINGAREA_AVG               169682
APARTMENTS_MODE                 156061
BASEMENTAREA_MODE               179943
YEARS_BEGINEXPLUATATION_MODE    150007
YEARS_BUILD_MODE                204488
COMMONAREA_MODE                 214865
ELEVATORS_MODE                  163891
ENTRANCES_MODE                  154828
FLOORSMAX_MODE                  153020
FLOORSMIN_MODE                  208642
LANDAREA_MODE                   182590
LIVINGAPARTMENTS_MODE           210199
LIVINGAREA_MODE                 154350
NONLIVINGAPARTMENTS_MODE        213514
NONLIVINGAREA_MODE              169682
APARTMENTS_MEDI                 156061
BASEMENTAREA_MEDI               179943
YEARS_BEGINEXPLUATATION_MEDI    150007
YEARS_BUILD_MEDI                204488
COMMONAREA_MEDI                 214865
ELEVATORS_MEDI                  163891
ENTRANCES_MEDI                  154828
FLOORSMAX_MEDI                  153020
FLOORSMIN_MEDI                  208642
LANDAREA_MEDI                   182590
LIVINGAPARTMENTS_MEDI           210199
LIVINGAREA_MEDI                 154350
NONLIVINGAPARTMENTS_MEDI        213514
NONLIVINGAREA_MEDI              169682
FONDKAPREMONT_MODE              210295
HOUSETYPE_MODE                  154297
TOTALAREA_MODE                  148431
WALLSMATERIAL_MODE              156341
EMERGENCYSTATE_MODE             145755
OBS_30_CNT_SOCIAL_CIRCLE          1021
DEF_30_CNT_SOCIAL_CIRCLE          1021
OBS_60_CNT_SOCIAL_CIRCLE          1021
DEF_60_CNT_SOCIAL_CIRCLE          1021
DAYS_LAST_PHONE_CHANGE               1
FLAG_DOCUMENT_2                      0
FLAG_DOCUMENT_3                      0
FLAG_DOCUMENT_4                      0
FLAG_DOCUMENT_5                      0
FLAG_DOCUMENT_6                      0
FLAG_DOCUMENT_7                      0
FLAG_DOCUMENT_8                      0
FLAG_DOCUMENT_9                      0
FLAG_DOCUMENT_10                     0
FLAG_DOCUMENT_11                     0
FLAG_DOCUMENT_12                     0
FLAG_DOCUMENT_13                     0
FLAG_DOCUMENT_14                     0
FLAG_DOCUMENT_15                     0
FLAG_DOCUMENT_16                     0
FLAG_DOCUMENT_17                     0
FLAG_DOCUMENT_18                     0
FLAG_DOCUMENT_19                     0
FLAG_DOCUMENT_20                     0
FLAG_DOCUMENT_21                     0
AMT_REQ_CREDIT_BUREAU_HOUR       41519
AMT_REQ_CREDIT_BUREAU_DAY        41519
AMT_REQ_CREDIT_BUREAU_WEEK       41519
AMT_REQ_CREDIT_BUREAU_MON        41519
AMT_REQ_CREDIT_BUREAU_QRT        41519
AMT_REQ_CREDIT_BUREAU_YEAR       41519
dtype: int64

#### Finding out columns with null values.

In [10]:
app.isnull().sum()[app.isnull().sum().values>0]

AMT_ANNUITY                         12
AMT_GOODS_PRICE                    278
NAME_TYPE_SUITE                   1292
OWN_CAR_AGE                     202929
OCCUPATION_TYPE                  96391
CNT_FAM_MEMBERS                      2
EXT_SOURCE_1                    173378
EXT_SOURCE_2                       660
EXT_SOURCE_3                     60965
APARTMENTS_AVG                  156061
BASEMENTAREA_AVG                179943
YEARS_BEGINEXPLUATATION_AVG     150007
YEARS_BUILD_AVG                 204488
COMMONAREA_AVG                  214865
ELEVATORS_AVG                   163891
ENTRANCES_AVG                   154828
FLOORSMAX_AVG                   153020
FLOORSMIN_AVG                   208642
LANDAREA_AVG                    182590
LIVINGAPARTMENTS_AVG            210199
LIVINGAREA_AVG                  154350
NONLIVINGAPARTMENTS_AVG         213514
NONLIVINGAREA_AVG               169682
APARTMENTS_MODE                 156061
BASEMENTAREA_MODE               179943
YEARS_BEGINEXPLUATATION_MODE    150007
YEARS_BUILD_MODE                204488
COMMONAREA_MODE                 214865
ELEVATORS_MODE                  163891
ENTRANCES_MODE                  154828
FLOORSMAX_MODE                  153020
FLOORSMIN_MODE                  208642
LANDAREA_MODE                   182590
LIVINGAPARTMENTS_MODE           210199
LIVINGAREA_MODE                 154350
NONLIVINGAPARTMENTS_MODE        213514
NONLIVINGAREA_MODE              169682
APARTMENTS_MEDI                 156061
BASEMENTAREA_MEDI               179943
YEARS_BEGINEXPLUATATION_MEDI    150007
YEARS_BUILD_MEDI                204488
COMMONAREA_MEDI                 214865
ELEVATORS_MEDI                  163891
ENTRANCES_MEDI                  154828
FLOORSMAX_MEDI                  153020
FLOORSMIN_MEDI                  208642
LANDAREA_MEDI                   182590
LIVINGAPARTMENTS_MEDI           210199
LIVINGAREA_MEDI                 154350
NONLIVINGAPARTMENTS_MEDI        213514
NONLIVINGAREA_MEDI              169682
FONDKAPREMONT_MODE              210295
HOUSETYPE_MODE                  154297
TOTALAREA_MODE                  148431
WALLSMATERIAL_MODE              156341
EMERGENCYSTATE_MODE             145755
OBS_30_CNT_SOCIAL_CIRCLE          1021
DEF_30_CNT_SOCIAL_CIRCLE          1021
OBS_60_CNT_SOCIAL_CIRCLE          1021
DEF_60_CNT_SOCIAL_CIRCLE          1021
DAYS_LAST_PHONE_CHANGE               1
AMT_REQ_CREDIT_BUREAU_HOUR       41519
AMT_REQ_CREDIT_BUREAU_DAY        41519
AMT_REQ_CREDIT_BUREAU_WEEK       41519
AMT_REQ_CREDIT_BUREAU_MON        41519
AMT_REQ_CREDIT_BUREAU_QRT        41519
AMT_REQ_CREDIT_BUREAU_YEAR       41519
dtype: int64

In [11]:
#number of columns having null values
len(app.isnull().sum()[app.isnull().sum().values>0])

67

In [12]:
#maximum number of null values in a column
max(app.isnull().sum().values)

214865

In [13]:
#minimum number of null values in a column
min(app.isnull().sum()[app.isnull().sum().values>0].values)

1

#### There are total 67 columns with null values.

#### Least number of null values in a column is 1 and most number of null values in a column is 214865

In [14]:
#Calculating % of number of null values for columns having null values
app.isnull().sum()[app.isnull().sum().values>0]/len(app)*100

AMT_ANNUITY                      0.003902
AMT_GOODS_PRICE                  0.090403
NAME_TYPE_SUITE                  0.420148
OWN_CAR_AGE                     65.990810
OCCUPATION_TYPE                 31.345545
CNT_FAM_MEMBERS                  0.000650
EXT_SOURCE_1                    56.381073
EXT_SOURCE_2                     0.214626
EXT_SOURCE_3                    19.825307
APARTMENTS_AVG                  50.749729
BASEMENTAREA_AVG                58.515956
YEARS_BEGINEXPLUATATION_AVG     48.781019
YEARS_BUILD_AVG                 66.497784
COMMONAREA_AVG                  69.872297
ELEVATORS_AVG                   53.295980
ENTRANCES_AVG                   50.348768
FLOORSMAX_AVG                   49.760822
FLOORSMIN_AVG                   67.848630
LANDAREA_AVG                    59.376738
LIVINGAPARTMENTS_AVG            68.354953
LIVINGAREA_AVG                  50.193326
NONLIVINGAPARTMENTS_AVG         69.432963
NONLIVINGAREA_AVG               55.179164
APARTMENTS_MODE                 50.749729
BASEMENTAREA_MODE               58.515956
YEARS_BEGINEXPLUATATION_MODE    48.781019
YEARS_BUILD_MODE                66.497784
COMMONAREA_MODE                 69.872297
ELEVATORS_MODE                  53.295980
ENTRANCES_MODE                  50.348768
FLOORSMAX_MODE                  49.760822
FLOORSMIN_MODE                  67.848630
LANDAREA_MODE                   59.376738
LIVINGAPARTMENTS_MODE           68.354953
LIVINGAREA_MODE                 50.193326
NONLIVINGAPARTMENTS_MODE        69.432963
NONLIVINGAREA_MODE              55.179164
APARTMENTS_MEDI                 50.749729
BASEMENTAREA_MEDI               58.515956
YEARS_BEGINEXPLUATATION_MEDI    48.781019
YEARS_BUILD_MEDI                66.497784
COMMONAREA_MEDI                 69.872297
ELEVATORS_MEDI                  53.295980
ENTRANCES_MEDI                  50.348768
FLOORSMAX_MEDI                  49.760822
FLOORSMIN_MEDI                  67.848630
LANDAREA_MEDI                   59.376738
LIVINGAPARTMENTS_MEDI           68.354953
LIVINGAREA_MEDI                 50.193326
NONLIVINGAPARTMENTS_MEDI        69.432963
NONLIVINGAREA_MEDI              55.179164
FONDKAPREMONT_MODE              68.386172
HOUSETYPE_MODE                  50.176091
TOTALAREA_MODE                  48.268517
WALLSMATERIAL_MODE              50.840783
EMERGENCYSTATE_MODE             47.398304
OBS_30_CNT_SOCIAL_CIRCLE         0.332021
DEF_30_CNT_SOCIAL_CIRCLE         0.332021
OBS_60_CNT_SOCIAL_CIRCLE         0.332021
DEF_60_CNT_SOCIAL_CIRCLE         0.332021
DAYS_LAST_PHONE_CHANGE           0.000325
AMT_REQ_CREDIT_BUREAU_HOUR      13.501631
AMT_REQ_CREDIT_BUREAU_DAY       13.501631
AMT_REQ_CREDIT_BUREAU_WEEK      13.501631
AMT_REQ_CREDIT_BUREAU_MON       13.501631
AMT_REQ_CREDIT_BUREAU_QRT       13.501631
AMT_REQ_CREDIT_BUREAU_YEAR      13.501631
dtype: float64

Now there's no literature available which states the exact rule of thumb specifying the percentage of acceptable null values.
But market standard says most of the times we can drop columns with more than 25-30% missing data, of-course with many exceptions as per the use case.

Also Here Occupation type lies in the border line with 31% null values. But we believe Occupation type plays a significant role to explore if it can be used to find whether the person will default or not. Hence we are deciding to drop columns columns with more than 40% of missing values(Since there's no value between 31-40%)

In [15]:
#Finding the number of columns having more than 30% rows with null values
len(app.isnull().sum()[app.isnull().sum().values>(0.40 * len(app))])

49

#### Listing down these 49 columns that are to be dropped:

BC itna ghatiya data maine apne zindagi me kabhi nai dekha.

In [16]:
insignificant_col1 = list(app.isnull().sum()[app.isnull().sum().values>(0.40 * len(app))].index)
print(insignificant_col1)
print(len(insignificant_col1))

['OWN_CAR_AGE', 'EXT_SOURCE_1', 'APARTMENTS_AVG', 'BASEMENTAREA_AVG', 'YEARS_BEGINEXPLUATATION_AVG', 'YEARS_BUILD_AVG', 'COMMONAREA_AVG', 'ELEVATORS_AVG', 'ENTRANCES_AVG', 'FLOORSMAX_AVG', 'FLOORSMIN_AVG', 'LANDAREA_AVG', 'LIVINGAPARTMENTS_AVG', 'LIVINGAREA_AVG', 'NONLIVINGAPARTMENTS_AVG', 'NONLIVINGAREA_AVG', 'APARTMENTS_MODE', 'BASEMENTAREA_MODE', 'YEARS_BEGINEXPLUATATION_MODE', 'YEARS_BUILD_MODE', 'COMMONAREA_MODE', 'ELEVATORS_MODE', 'ENTRANCES_MODE', 'FLOORSMAX_MODE', 'FLOORSMIN_MODE', 'LANDAREA_MODE', 'LIVINGAPARTMENTS_MODE', 'LIVINGAREA_MODE', 'NONLIVINGAPARTMENTS_MODE', 'NONLIVINGAREA_MODE', 'APARTMENTS_MEDI', 'BASEMENTAREA_MEDI', 'YEARS_BEGINEXPLUATATION_MEDI', 'YEARS_BUILD_MEDI', 'COMMONAREA_MEDI', 'ELEVATORS_MEDI', 'ENTRANCES_MEDI', 'FLOORSMAX_MEDI', 'FLOORSMIN_MEDI', 'LANDAREA_MEDI', 'LIVINGAPARTMENTS_MEDI', 'LIVINGAREA_MEDI', 'NONLIVINGAPARTMENTS_MEDI', 'NONLIVINGAREA_MEDI', 'FONDKAPREMONT_MODE', 'HOUSETYPE_MODE', 'TOTALAREA_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE']
49

In [17]:
#Dropping these columns
app.drop(labels=insignificant_col1, axis=1, inplace=True)
app.shape

(307511, 73)

In [18]:
#Rest of the remaining columns having null values
app.isnull().sum()[app.isnull().sum()>0]

AMT_ANNUITY                      12
AMT_GOODS_PRICE                 278
NAME_TYPE_SUITE                1292
OCCUPATION_TYPE               96391
CNT_FAM_MEMBERS                   2
EXT_SOURCE_2                    660
EXT_SOURCE_3                  60965
OBS_30_CNT_SOCIAL_CIRCLE       1021
DEF_30_CNT_SOCIAL_CIRCLE       1021
OBS_60_CNT_SOCIAL_CIRCLE       1021
DEF_60_CNT_SOCIAL_CIRCLE       1021
DAYS_LAST_PHONE_CHANGE            1
AMT_REQ_CREDIT_BUREAU_HOUR    41519
AMT_REQ_CREDIT_BUREAU_DAY     41519
AMT_REQ_CREDIT_BUREAU_WEEK    41519
AMT_REQ_CREDIT_BUREAU_MON     41519
AMT_REQ_CREDIT_BUREAU_QRT     41519
AMT_REQ_CREDIT_BUREAU_YEAR    41519
dtype: int64

Not getting the meaning of AMT_ANNUITY. Since it is only 12 columns we can impute it.

In [19]:
print("AMT_ANNUITY")
print('Mean: ', app['AMT_ANNUITY'].mean())
print('Median: ', app['AMT_ANNUITY'].median())
print('Mode: ', app['AMT_ANNUITY'].mode())

print("----------------------------------")
print("AMT_GOODS_PRICE")
print('Mean: ', app['AMT_GOODS_PRICE'].mean())
print('Median: ', app['AMT_GOODS_PRICE'].median())
print('Mode: ', app['AMT_GOODS_PRICE'].mode())

AMT_ANNUITY
Mean:  27108.573909183444
Median:  24903.0
Mode:  0    9000.0
dtype: float64
----------------------------------
AMT_GOODS_PRICE
Mean:  538396.2074288895
Median:  450000.0
Mode:  0    450000.0
dtype: float64

In [20]:
app[app['AMT_ANNUITY'].isnull()]

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_2,EXT_SOURCE_3,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
47531,155054,0,Cash loans,M,N,N,0,180000.0,450000.0,NaN,450000.0,Unaccompanied,Commercial associate,Incomplete higher,Single / not married,House / apartment,0.026392,-10668,-2523,-4946.0,-3238,1,1,1,1,1,0,High skill tech staff,1.0,2,2,WEDNESDAY,13,0,0,0,0,0,0,Business Entity Type 3,0.626896,0.372334,1.0,0.0,1.0,0.0,-2.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
50035,157917,0,Cash loans,F,N,N,0,94500.0,450000.0,NaN,450000.0,Unaccompanied,Working,Lower secondary,Civil marriage,House / apartment,0.035792,-9027,-1270,-3640.0,-741,1,1,1,1,0,0,Laborers,2.0,2,2,MONDAY,20,0,0,0,0,0,0,Business Entity Type 1,0.727274,0.468660,0.0,0.0,0.0,0.0,-706.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
51594,159744,0,Cash loans,F,N,N,0,202500.0,539100.0,NaN,450000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.046220,-17376,-3950,-11524.0,-831,1,1,0,1,0,0,Cooking staff,2.0,1,1,WEDNESDAY,15,0,0,0,1,1,1,Self-employed,0.738370,0.452534,1.0,0.0,1.0,0.0,-199.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
55025,163757,0,Cash loans,F,N,N,0,162000.0,296280.0,NaN,225000.0,Unaccompanied,State servant,Higher education,Married,House / apartment,0.035792,-11329,-2040,-3195.0,-3069,1,1,0,1,0,0,Core staff,2.0,2,2,FRIDAY,13,0,0,0,1,1,1,Government,0.566316,0.220095,0.0,0.0,0.0,0.0,-2841.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,4.0
59934,169487,0,Cash loans,M,Y,N,0,202500.0,360000.0,NaN,360000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.046220,-19762,-2498,-11285.0,-3305,1,1,1,1,1,0,Laborers,1.0,1,1,FRIDAY,15,0,1,1,0,1,1,Other,0.583947,0.177704,0.0,0.0,0.0,0.0,-743.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,1.0,0.0,0.0,6.0
75873,187985,0,Cash loans,M,Y,N,0,144000.0,219249.0,NaN,166500.0,Unaccompanied,Working,Higher education,Single / not married,Rented apartment,0.022800,-20831,-2450,-771.0,-4203,1,1,0,1,0,0,Drivers,1.0,2,2,FRIDAY,15,0,0,0,0,0,0,Business Entity Type 3,0.667564,0.425893,0.0,0.0,0.0,0.0,-1986.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,11.0
89343,203726,0,Cash loans,F,Y,N,0,90000.0,157500.0,NaN,157500.0,Unaccompanied,State servant,Secondary / secondary special,Married,House / apartment,0.015221,-12134,-3721,-858.0,-591,1,1,0,1,1,0,Medicine staff,2.0,2,2,WEDNESDAY,11,0,0,0,0,0,0,Medicine,0.154811,0.297087,0.0,0.0,0.0,0.0,-348.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,2.0,0.0,0.0
123872,243648,0,Cash loans,F,N,Y,0,202500.0,929088.0,NaN,720000.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.019689,-13902,-3540,-168.0,-4250,1,1,0,1,0,1,Secretaries,2.0,2,2,SATURDAY,12,0,0,0,0,0,0,Self-employed,0.510934,0.581484,0.0,0.0,0.0,0.0,-1331.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,5.0
207186,340147,0,Cash loans,M,N,N,0,171000.0,486000.0,NaN,486000.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.018634,-10151,-472,-10127.0,-2787,1,1,0,1,1,0,Security staff,2.0,2,2,WEDNESDAY,13,1,1,1,1,1,1,Security,0.706306,0.391055,0.0,0.0,0.0,0.0,-295.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,1.0,1.0,0.0,2.0
227939,364022,0,Cash loans,F,N,Y,0,315000.0,628069.5,NaN,499500.0,Unaccompanied,Commercial associate,Higher education,Married,Municipal apartment,0.046220,-16344,-1478,-482.0,-4192,1,1,0,1,0,0,Sales staff,2.0,1,1,WEDNESDAY,11,0,1,1,0,0,0,Business Entity Type 3,0.618698,0.431192,1.0,0.0,1.0,0.0,-1255.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,1.0,0.0,0.0,2.0
239329,377174,0,Cash loans,F,N,Y,0,157500.0,792000.0,NaN,792000.0,Family,State servant,Secondary / secondary special,Married,House / apartment,0.026392,-17661,-2885,-8594.0,-1221,1,1,0,1,1,0,Managers,2.0,2,2,SATURDAY,14,0,0,0,0,0,0,Other,0.656305,0.651260,0.0,0.0,0.0,0.0,-322.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
241835,379997,0,Cash loans,F,N,N,0,315000.0,1483231.5,NaN,1354500.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.072508,-15072,-152,-7576.0,-4389,1,1,1,1,1,0,Accountants,2.0,1,1,WEDNESDAY,15,0,1,1,0,1,1,Self-employed,0.267269,NaN,0.0,0.0,0.0,0.0,-504.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

Looking at the AMT_CREDIT for rows with AMT_ANNUITY null values, replacing null values with mode doesn't seem to be a good idea. Hence replacing the null values with median.

In [21]:
app['AMT_ANNUITY'].fillna((app['AMT_ANNUITY'].median()), inplace=True)

In [22]:
app[app['AMT_GOODS_PRICE'].isnull()]

        SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
724         100837       0    Revolving loans           F            N
5937        106955       0    Revolving loans           F            N
6425        107494       0    Revolving loans           F            N
6703        107822       0    Revolving loans           F            N
7647        108913       0    Revolving loans           M            N
7880        109190       1    Revolving loans           F            N
7995        109322       0    Revolving loans           M            N
10819       112595       0    Revolving loans           F            N
11287       113148       0    Revolving loans           F            N
13008       115162       0    Revolving loans           F            N
14699       117150       0    Revolving loans           M            N
15953       118618       0    Revolving loans           F            N
18935       122080       0    Revolving loans           M            N
19178       122374       0    Revolving loans           F            N
19921       123233       0    Revolving loans           F            N
21193       124697       0    Revolving loans           F            N
21338       124859       0    Revolving loans           M            N
21546       125096       0    Revolving loans           F            N
25391       129532       0    Revolving loans           M            N
26398       130692       0    Revolving loans           M            N
26736       131077       0    Revolving loans           F            N
27003       131385       0    Revolving loans           M            N
28201       132778       0    Revolving loans           F            N
29059       133761       0    Revolving loans           F            N
30164       135010       0    Revolving loans           F            N
30294       135159       0    Revolving loans           M            N
32143       137268       0    Revolving loans           M            N
36250       141975       0    Revolving loans           F            N
36721       142532       0    Revolving loans           M            N
39230       145435       0    Revolving loans           F            N
40571       146988       0    Revolving loans           F            N
41099       147593       1    Revolving loans           F            N
41161       147655       0    Revolving loans           M            N
41982       148605       0    Revolving loans           M            N
42024       148658       0    Revolving loans           F            N
43630       150507       0    Revolving loans           M            N
45657       152889       0    Revolving loans           M            N
47627       155169       0    Revolving loans           F            N
50540       158525       1    Revolving loans           F            N
52711       161052       0    Revolving loans           M            N
52955       161332       0    Revolving loans           F            N
54045       162615       0    Revolving loans           F            N
55600       164423       0    Revolving loans           F            N
56002       164897       1    Revolving loans           F            N
58595       167920       0    Revolving loans           F            N
58653       167989       0    Revolving loans           M            N
60622       170291       0    Revolving loans           M            N
61022       170764       0    Revolving loans           F            N
61072       170823       0    Revolving loans           F            N
61618       171462       0    Revolving loans           M            N
63319       173434       0    Revolving loans           F            N
64118       174350       0    Revolving loans           F            N
64184       174427       0    Revolving loans           F            N
66168       176745       0    Revolving loans           M            N
67609       178403       0    Revolving loans           M            N
69461       180561       1    Revolving loans           F            N
69525       180635       0    Revolving loans           F            N
70661       181966       0    Revolving loans           F            N
70731       182043       0    Revolving loans           F            N
72166       183693       0    Revolving loans           F            N
72902       184538       0    Revolving loans           F            N
74676       186598       0    Revolving loans           M            N
75036       187023       0    Revolving loans           F            N
78786       191335       1    Revolving loans           F            N
79108       191700       0    Revolving loans           F            N
79484       192140       0    Revolving loans           M            N
80669       193529       0    Revolving loans           F            N
83784       197173       0    Revolving loans           F            N
85172       198819       0    Revolving loans           F            N
85861       199632       0    Revolving loans           F            N
86000       199789       1    Revolving loans           F            N
86005       199794       1    Revolving loans           F            N
87095       201085       0    Revolving loans           F            N
87144       201141       0    Revolving loans           F            N
87226       201232       0    Revolving loans           F            N
88544       202806       0    Revolving loans           F            N
89085       203438       0    Revolving loans           F            N
89698       204141       0    Revolving loans           F            N
90898       205537       0    Revolving loans           M            N
96192       211675       0    Revolving loans           F            N
97022       212618       0    Revolving loans           F            N
102123      218557       0    Revolving loans           F            N
102245      218700       0    Revolving loans           M            N
106630      223714       0    Revolving loans           F            N
107559      224784       0    Revolving loans           M            N
107715      224966       0    Revolving loans           F            N
110972      228738       0    Revolving loans           F            N
112566      230576       0    Revolving loans           F            N
113036      231102       0    Revolving loans           F            N
113251      231347       0    Revolving loans           F            N
113449      231576       0    Revolving loans           F            N
114314      232572       0    Revolving loans           M            N
114788      233103       0    Revolving loans           F            N
116575      235188       0    Revolving loans           F            N
117302      236029       0    Revolving loans           M            N
117471      236212       0    Revolving loans           F            N
117483      236227       0    Revolving loans           F            N
123354      243050       0    Revolving loans           F            N
124123      243942       0    Revolving loans           M            N
124436      244308       0    Revolving loans           F            N
124770      244697       1    Revolving loans           F            N
128354      248885       0    Revolving loans           F            N
129705      250439       0    Revolving loans           F            N
130737      251638       0    Revolving loans           F            N
130800      251708       0    Revolving loans           F            N
131669      252707       0    Revolving loans           F            N
132208      253336       0    Revolving loans           M            N
133526      254865       0    Revolving loans           M            N
133548      254889       0    Revolving loans           F            N
134298      255767       0    Revolving loans           F            N
134327      255803       0    Revolving loans           F            N
136330      258130       0    Revolving loans           M            N
136424      258241       0    Revolving loans           F            N
137091      259002       0    Revolving loans           M            N
137354      259301       0    Revolving loans           M            N
137374      259325       0    Revolving loans           F            N
139558      261811       0    Revolving loans           M            N
142605      265357       0    Revolving loans           F            N
143606      266519       0    Revolving loans           F            N
145137      268295       0    Revolving loans           M            N
145278      268463       0    Revolving loans           F            N
145594      268818       0    Revolving loans           F            N
147294      270776       0    Revolving loans           F            N
149045      272806       0    Revolving loans           F            N
149111      272877       0    Revolving loans           F            N
149562      273397       0    Revolving loans           F            N
150425      274382       0    Revolving loans           M            N
152608      276875       0    Revolving loans           F            N
152898      277210       1    Revolving loans           F            N
153801      278254       1    Revolving loans           F            N
155673      280456       0    Revolving loans           F            N
155716      280504       0    Revolving loans           F            N
156456      281353       0    Revolving loans           M            N
158563      283824       0    Revolving loans           M            N
158785      284082       0    Revolving loans           F            N
161730      287492       0    Revolving loans           F            N
163709      289773       0    Revolving loans           F            N
163889      289983       0    Revolving loans           F            N
167777      294482       0    Revolving loans           F            N
168169      294934       0    Revolving loans           M            N
168588      295417       0    Revolving loans           F            N
169101      296002       0    Revolving loans           F            N
176663      304718       0    Revolving loans           F            N
179626      308153       0    Revolving loans           M            N
180925      309672       0    Revolving loans           F            N
183381      312551       0    Revolving loans           F            N
184811      314222       0    Revolving loans           M            N
186634      316367       1    Revolving loans           M            N
187032      316821       0    Revolving loans           F            N
187120      316922       0    Revolving loans           M            N
187145      316954       0    Revolving loans           M            N
187167      316976       0    Revolving loans           F            N
187348      317181       0    Revolving loans           F            N
188475      318512       0    Revolving loans           F            N
190113      320433       1    Revolving loans           F            N
191858      322471       0    Revolving loans           F            N
193826      324762       0    Revolving loans           F            N
195008      326127       0    Revolving loans           F            N
195851      327096       0    Revolving loans           F            N
195936      327191       0    Revolving loans           M            N
197105      328529       0    Revolving loans           F            N
197647      329156       0    Revolving loans           F            N
199643      331445       0    Revolving loans           F            N
200312      332213       0    Revolving loans           F            N
201823      333949       0    Revolving loans           F            N
202896      335206       0    Revolving loans           F            N
204519      337101       0    Revolving loans           F            N
206222      339033       0    Revolving loans           F            N
207015      339947       0    Revolving loans           F            N
209338      342625       0    Revolving loans           F            N
209657      342986       0    Revolving loans           M            N
210718      344187       1    Revolving loans           F            N
211090      344622       0    Revolving loans           F            N
214803      348904       1    Revolving loans           F            N
215137      349287       0    Revolving loans           M            N
215656      349877       0    Revolving loans           F            N
216059      350347       0    Revolving loans           M            N
216762      351158       0    Revolving loans           F            N
216996      351432       0    Revolving loans           M            N
218083      352663       0    Revolving loans           M            N
218140      352730       0    Revolving loans           F            N
218981      353686       0    Revolving loans           M            N
219070      353787       0    Revolving loans           F            N
219075      353792       0    Revolving loans           F            N
221204      356244       0    Revolving loans           F            N
223226      358555       0    Revolving loans           F            N
223502      358867       0    Revolving loans           M            N
225994      361759       0    Revolving loans           F            N
226725      362616       1    Revolving loans           F            N
227450      363460       0    Revolving loans           M            N
229877      366256       1    Revolving loans           M            N
229923      366310       0    Revolving loans           F            N
230455      366938       0    Revolving loans           M            N
230484      366971       0    Revolving loans           F            N
233542      370507       0    Revolving loans           F            N
236260      373660       0    Revolving loans           M            N
236624      374077       0    Revolving loans           M            N
236974      374479       0    Revolving loans           F            N
237074      374594       0    Revolving loans           M            N
239491      377340       0    Revolving loans           F            N
239835      377705       0    Revolving loans           F            N
240223      378214       0    Revolving loans           F            N
242000      380194       0    Revolving loans           F            N
242020      380214       0    Revolving loans           F            N
242307      380511       0    Revolving loans           F            N
242644      380891       0    Revolving loans           M            N
243268      381622       0    Revolving loans           F            N
244620      383122       0    Revolving loans           M            N
244962      383538       0    Revolving loans           M            N
245542      384157       0    Revolving loans           F            N
246989      385808       0    Revolving loans           F            N
247473      386374       0    Revolving loans           F            N
248749      387780       0    Revolving loans           F            N
249109      388225       0    Revolving loans           M            N
249616      388813       1    Revolving loans           F            N
253126      392897       1    Revolving loans           M            N
254451      394441       0    Revolving loans           F            N
255049      395122       0    Revolving loans           M            N
256395      396696       0    Revolving loans           M            N
256843      397231       0    Revolving loans           F            N
257017      397421       0    Revolving loans           F            N
257118      397542       0    Revolving loans           M            N
257405      397874       0    Revolving loans           M            N
259788      400636       0    Revolving loans           M            N
260704      401702       1    Revolving loans           F            N
262052      403332       0    Revolving loans           M            N
262572      404012       0    Revolving loans           M            N
262657      404102       0    Revolving loans           F            N
262853      404359       0    Revolving loans           F            N
263035      404580       0    Revolving loans           M            N
263213      404774       0    Revolving loans           M            N
267302      409698       0    Revolving loans           F            N
267335      409733       0    Revolving loans           F            N
267367      409768       0    Revolving loans           F            N
269291      412079       0    Revolving loans           M            N
270616      413674       1    Revolving loans           F            N
271074      414243       0    Revolving loans           F            N
271339      414555       0    Revolving loans           F            N
271611      414876       0    Revolving loans           M            N
271754      415039       0    Revolving loans           M            N
272242      415625       0    Revolving loans           M            N
272252      415635       0    Revolving loans           F            N
273229      416712       0    Revolving loans           F            N
273757      417309       0    Revolving loans           F            N
275284      419023       0    Revolving loans           M            N
275429      419205       0    Revolving loans           F            N
276692      420659       0    Revolving loans           M            N
277969      422096       0    Revolving loans           F            N
278747      422928       0    Revolving loans           M            N
279583      423902       0    Revolving loans           F            N
279997      424410       0    Revolving loans           F            N
281050      425623       0    Revolving loans           M            N
281653      426277       0    Revolving loans           F            N
282002      426638       0    Revolving loans           M            N
282270      426914       0    Revolving loans           F            N
282847      427592       0    Revolving loans           F            N
283159      427953       0    Revolving loans           F            N
285269      430381       0    Revolving loans           M            N
287092      432536       0    Revolving loans           M            N
287347      432847       0    Revolving loans           F            N
289793      435732       0    Revolving loans           F            N
291372      437555       0    Revolving loans           F            N
291384      437568       0    Revolving loans           M            N
292040      438322       0    Revolving loans           F            N
292120      438413       0    Revolving loans           F            N
294136      440763       0    Revolving loans           F            N
295295      442115       0    Revolving loans           F            N
298004      445250       0    Revolving loans           M            N
300107      447675       0    Revolving loans           F            N
302923      450959       0    Revolving loans           F            N
303603      451760       0    Revolving loans           F            N
303621      451781       0    Revolving loans           F            N
304621      452926       0    Revolving loans           F            N
304678      452992       0    Revolving loans           F            N
304784      453120       0    Revolving loans           M            N
305833      454341       0    Revolving loans           F            N
306126      454683       0    Revolving loans           M            N
306273      454852       0    Revolving loans           M            N

       FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  \
724                  Y             2           45000.0    135000.0

Null values of AMT_GOODS_PRICE will have to be imputed using mode.

In [23]:
app['AMT_GOODS_PRICE'].fillna((app['AMT_GOODS_PRICE'].median()), inplace=True)

There are still columns with more than 40000 null values. On examining those columns, they won't be of any significance further in our analysis. Dropping those columns.

In [31]:
insignificant_col2=list(app.isnull().sum()[app.isnull().sum().values>40000].index)
insignificant_col2
app.drop(labels=insignificant_col2, axis=1, inplace=True)
app.isnull().sum()[app.isnull().sum().values>0]

NAME_TYPE_SUITE             1292
CNT_FAM_MEMBERS                2
EXT_SOURCE_2                 660
OBS_30_CNT_SOCIAL_CIRCLE    1021
DEF_30_CNT_SOCIAL_CIRCLE    1021
OBS_60_CNT_SOCIAL_CIRCLE    1021
DEF_60_CNT_SOCIAL_CIRCLE    1021
DAYS_LAST_PHONE_CHANGE         1
dtype: int64

On further examination, the columns NAME_TYPE_SUITE and EXT_SOURCE_2 seemed insignificant. Hence dropping those columns.

In [33]:
insignificant_col3=['NAME_TYPE_SUITE', 'EXT_SOURCE_2']
app.drop(labels=insignificant_col3, axis=1, inplace=True)
app.isnull().sum()[app.isnull().sum().values>0]

CNT_FAM_MEMBERS                2
OBS_30_CNT_SOCIAL_CIRCLE    1021
DEF_30_CNT_SOCIAL_CIRCLE    1021
OBS_60_CNT_SOCIAL_CIRCLE    1021
DEF_60_CNT_SOCIAL_CIRCLE    1021
DAYS_LAST_PHONE_CHANGE         1
dtype: int64

Imputing the 2 missing values for CNT_FAM_MEMBERS with mode since mean can give incorrect values and median will give the value in center. Since only 2 rows are impacted going for the most occured value.

Dropping the row which has missing value in column DAYS_LAST_PHONE_CHANGE .

In [34]:
app['CNT_FAM_MEMBERS'].fillna((app['CNT_FAM_MEMBERS'].mode()), inplace=True)